spring:
  datasource:
    url: jdbc:mysql://192.168.193.62:3306/uploadfile?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123456
  jpa:
    show-sql: true
  mvc:
    view:
      prefix: /templates/
      suffix: .ftl
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB

server:
  servlet:
    context-path: /bigfile
  port: 39090

